
import Footer from "@/app/components/Footer";
import Navbar from "@/app/components/Navbar";
import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

const grown = localFont({
  src: '/Fonts/GrownPersonalUse-0Wa7P.ttf',
  display: 'swap',
  variable: '--font-grown',
});

const montserrat = Montserrat_Alternates({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${grown.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
